# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CosmosRatingTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CosmosRatingTutorial
	pod 'Cosmos'

  target 'CosmosRatingTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CosmosRatingTutorialUITests' do
    # Pods for testing
  end

end
